# Rustfmt configuration for synthphone_vocals
# Only using stable features

# Edition
edition = "2021"

# Maximum width of each line
max_width = 100

# Maximum width of the args of a function call before falling back to vertical formatting
fn_call_width = 80

# Maximum width of a struct literal before falling back to vertical formatting
struct_lit_width = 80

# Maximum width of a struct variant before falling back to vertical formatting
struct_variant_width = 80

# Maximum width of an array literal before falling back to vertical formatting
array_width = 80

# Maximum width of a chain to fit on a single line
chain_width = 80

# Maximum width of the args of a function-like attributes before falling back to vertical formatting
attr_fn_like_width = 80

# Use field init shorthand if possible
use_field_init_shorthand = true

# Use small heuristics for formatting
use_small_heuristics = "Default"

# Reorder imports and extern crates
reorder_imports = true
reorder_modules = true

# Merge multiple derives into a single one
merge_derives = true

# Use try shorthand
use_try_shorthand = false

# Remove nested parens
remove_nested_parens = true

# Tab spaces
tab_spaces = 4

# Hard tabs
hard_tabs = false

# Newline style
newline_style = "Unix"
