name: Feature Request
description: Suggest a new feature or enhancement for synthphone_vocals
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

        Please search existing issues and discussions before creating a new feature request.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear description of the feature you'd like to see added
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Currently, when I try to...
        I encounter the problem that...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: I think we could solve this by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Why the proposed solution is better: ...

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New algorithm/DSP functionality
        - Performance improvement
        - API enhancement
        - Documentation improvement
        - Developer tooling
        - Platform support
        - Other
    validations:
      required: true

  - type: dropdown
    id: target-environment
    attributes:
      label: Target Environment
      description: Which environments should this feature support?
      multiple: true
      options:
        - Desktop (std)
        - Embedded (no_std)
        - Both environments
        - Don't care

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Cannot use library without this
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Detailed Use Case
      description: Provide a detailed description of how you would use this feature
      placeholder: |
        In my application, I would use this feature to...
        The workflow would be:
        1. ...
        2. ...
        3. ...

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Show how you envision the API would look (pseudo-code is fine)
      render: rust
      placeholder: |
        // Example of how the feature might be used
        use synthphone_vocals::*;

        fn example() {
            // Your proposed API usage here
        }

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented? (Optional)
      placeholder: |
        This could potentially be implemented by...
        Some considerations might be...

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to the existing API?
      options:
        - No - Purely additive
        - Maybe - Might need minor API changes
        - Yes - Would require breaking changes
        - Not sure
    validations:
      required: true

  - type: textarea
    id: performance-impact
    attributes:
      label: Performance Considerations
      description: What performance impact (if any) might this feature have?
      placeholder: |
        This feature might impact performance by...
        Memory usage considerations...
        Compute complexity...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be interested in implementing this feature myself
        - label: I would be willing to help test this feature
        - label: I can provide detailed feedback during development

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, research, or examples about the feature request here
      placeholder: |
        Related libraries/implementations:
        Academic papers or references:
        Additional examples:

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions for similar feature requests
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: This feature aligns with the goals of synthphone_vocals (real-time audio processing)
          required: true
